# -*- coding: utf-8 -*-
"""Chronic Kidney Disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RsQHVBluBRnsiDQGErKHDLiqSiSMCem
"""

"""
============================================================
  Chronic Kidney Disease (CKD) Classification Pipeline
  Research Paper Code  |  Dataset: 83,672 rows × 55 cols
  ► Stratified sample of 5,000 rows used for fast training
    (completes in < 5 minutes on any standard machine)
  ► Dual Experiment: Full Features vs Leakage-Free
============================================================
"""

# ── 0. IMPORTS ────────────────────────────────────────────
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time
import copy

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix,
    roc_auc_score, roc_curve, ConfusionMatrixDisplay,
    precision_score, recall_score, f1_score
)
from sklearn.linear_model    import LogisticRegression
from sklearn.tree            import DecisionTreeClassifier
from sklearn.ensemble        import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.svm             import SVC
from sklearn.neighbors       import KNeighborsClassifier
from sklearn.naive_bayes     import GaussianNB

# ── OPTIONAL IMPORTS (safe, skip if not installed) ────────
try:
    from xgboost import XGBClassifier
    XGBOOST_AVAILABLE = True
except:
    XGBClassifier = None
    XGBOOST_AVAILABLE = False

try:
    from lightgbm import LGBMClassifier
    LGBM_AVAILABLE = True
except:
    LGBMClassifier = None
    LGBM_AVAILABLE = False

try:
    from imblearn.over_sampling import SMOTE
    SMOTE_AVAILABLE = True
except:
    SMOTE_AVAILABLE = False

try:
    import shap
    SHAP_AVAILABLE = True
except:
    SHAP_AVAILABLE = False

print("=" * 62)
print("  CKD CLASSIFICATION — RESEARCH PIPELINE")
print("=" * 62)


# ── HELPER: reusable model evaluation pipeline ────────────
def run_experiment(X_tr, X_te, y_tr, y_te, models_dict,
                   scaled_models_set, Xtr_sc, Xte_sc, label=""):
    """
    Trains and evaluates all models. Returns results_df and roc_data dict.
    """
    cv       = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
    results  = []
    roc_data = {}

    print(f"\n  [{label}] Training {len(models_dict)} models ...")
    for name, model in models_dict.items():
        t0  = time.time()
        Xtr = Xtr_sc if name in scaled_models_set else X_tr
        Xte = Xte_sc if name in scaled_models_set else X_te

        try:
            cv_scores = cross_val_score(model, Xtr, y_tr, cv=cv,
                                        scoring="accuracy", n_jobs=-1)
            model.fit(Xtr, y_tr)
            y_pred  = model.predict(Xte)
            y_proba = model.predict_proba(Xte)[:, 1]

            acc  = accuracy_score(y_te, y_pred)
            auc  = roc_auc_score(y_te, y_proba)
            prec = precision_score(y_te, y_pred, zero_division=0)
            rec  = recall_score(y_te, y_pred, zero_division=0)
            f1   = f1_score(y_te, y_pred, zero_division=0)
            elapsed = time.time() - t0

            roc_data[name] = roc_curve(y_te, y_proba)
            results.append({
                "Model"          : name,
                "CV Acc (mean)"  : round(cv_scores.mean(), 4),
                "CV Acc (std)"   : round(cv_scores.std(),  4),
                "Test Accuracy"  : round(acc,  4),
                "Precision"      : round(prec, 4),
                "Recall"         : round(rec,  4),
                "F1-Score"       : round(f1,   4),
                "ROC-AUC"        : round(auc,  4),
                "Train Time (s)" : round(elapsed, 2),
            })
            print(f"    ✓ {name:<25}  Acc: {acc:.4f}  AUC: {auc:.4f}  F1: {f1:.4f}  [{elapsed:.1f}s]")
        except Exception as e:
            print(f"    ✗ {name:<25}  SKIPPED → {e}")

    results_df = pd.DataFrame(results).sort_values("Test Accuracy", ascending=False)
    return results_df, roc_data


from google.colab import files
uploaded = files.upload()

# ── 1. LOAD DATA ──────────────────────────────────────────
DATA_PATH    = "Chronickidneydiseases.csv"
SAMPLE_N     = 5000
RANDOM_STATE = 42

df_full = pd.read_csv(DATA_PATH)
print(f"\n[1] Full dataset  →  Rows: {df_full.shape[0]:,}  |  Cols: {df_full.shape[1]}")


# ── 2. BASIC EDA ON FULL DATA ─────────────────────────────
print("\n[2] Target (Diagnosis) distribution — full dataset:")
print(df_full["Diagnosis"].value_counts().rename({1: "CKD (1)", 0: "Not CKD (0)"}).to_string())
print(f"\n    Missing values in full dataset : {df_full.isnull().sum().sum()}")
print(f"\n    Adherence distribution:\n{df_full['Adherence'].value_counts().to_string()}")


# ── 3. STRATIFIED SAMPLE ──────────────────────────────────
from sklearn.model_selection import train_test_split as _tts
idx, _ = _tts(
    df_full.index, train_size=SAMPLE_N,
    stratify=df_full["Diagnosis"], random_state=RANDOM_STATE
)
df = df_full.loc[idx].reset_index(drop=True)

print(f"\n[3] Working sample (stratified) → {len(df):,} rows")
print("    Sample class balance:")
print(df["Diagnosis"].value_counts().rename({1: "CKD (1)", 0: "Not CKD (0)"}).to_string())


# ── 4. PREPROCESSING ──────────────────────────────────────
print("\n[4] Preprocessing ...")

drop_cols = ["PatientID", "RecommendedVisitsPerMonth"]
df.drop(columns=drop_cols, inplace=True, errors="ignore")

le = LabelEncoder()
df["Adherence"] = le.fit_transform(df["Adherence"])

TARGET = "Diagnosis"
X = df.drop(columns=[TARGET])
y = df[TARGET]

print(f"    Features used : {X.shape[1]}")
print(f"    No missing values: {X.isnull().sum().sum() == 0}")


# ── 5. TRAIN / TEST SPLIT ─────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)
print(f"\n[5] Split → Train: {len(X_train):,}  |  Test: {len(X_test):,}")

scaler        = StandardScaler()
X_train_sc    = scaler.fit_transform(X_train)
X_test_sc     = scaler.transform(X_test)
scaled_models = {"Logistic Regression", "SVM", "KNN"}


# ── 5b. OPTIONAL SMOTE (training data only) ───────────────
if SMOTE_AVAILABLE:
    try:
        sm = SMOTE(random_state=RANDOM_STATE)
        X_train, y_train = sm.fit_resample(X_train, y_train)
        X_train_sc = scaler.fit_transform(X_train)
        X_test_sc  = scaler.transform(X_test)
        print(f"\n[5b] SMOTE applied → New training size: {len(X_train):,}")
        print(f"     Class balance after SMOTE:\n{pd.Series(y_train).value_counts().to_string()}")
    except Exception as e:
        print(f"\n[5b] SMOTE skipped: {e}")
else:
    print("\n[5b] SMOTE not available (imblearn not installed) — skipping.")


# ── 5c. LEAKAGE-FREE DATASET ──────────────────────────────
print("\n[5c] Creating leakage-free dataset ...")

LEAKAGE_COLS = ["GFR", "SerumCreatinine", "BUNLevels", "ProteinInUrine", "ACR"]
X_no_leakage = X.drop(columns=LEAKAGE_COLS, errors="ignore")
removed = [c for c in LEAKAGE_COLS if c in X.columns]
print(f"    Removed {len(removed)} leakage columns: {removed}")
print(f"    Features remaining: {X_no_leakage.shape[1]}")

X_tr_nl, X_te_nl, y_tr_nl, y_te_nl = train_test_split(
    X_no_leakage, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)

if SMOTE_AVAILABLE:
    try:
        sm_nl = SMOTE(random_state=RANDOM_STATE)
        X_tr_nl, y_tr_nl = sm_nl.fit_resample(X_tr_nl, y_tr_nl)
        print(f"    SMOTE applied to no-leakage split → {len(X_tr_nl):,} rows")
    except Exception as e:
        print(f"    SMOTE skipped for no-leakage split: {e}")

scaler_nl  = StandardScaler()
X_tr_nl_sc = scaler_nl.fit_transform(X_tr_nl)
X_te_nl_sc = scaler_nl.transform(X_te_nl)


# ── 6. EDA PLOTS ──────────────────────────────────────────
print("\n[6] Generating EDA plots ...")

# 6a. Class distribution
plt.figure(figsize=(5, 4))
counts = y.value_counts().rename({1: "CKD", 0: "Not CKD"})
counts.plot(kind="bar", color=["tomato", "steelblue"], edgecolor="black")
plt.title("Class Distribution (Sample)", fontsize=13)
plt.ylabel("Count"); plt.xticks(rotation=0)
for i, v in enumerate(counts): plt.text(i, v + 3, str(v), ha="center", fontsize=10)
plt.tight_layout(); plt.savefig("class_distribution.png", dpi=150); plt.close()

# 6b. Age distribution by class
plt.figure(figsize=(7, 4))
for label, color in zip([0, 1], ["steelblue", "tomato"]):
    df[df[TARGET] == label]["Age"].plot(
        kind="hist", bins=25, alpha=0.6,
        color=color, label="CKD" if label == 1 else "Not CKD", edgecolor="black"
    )
plt.xlabel("Age"); plt.title("Age Distribution by CKD Status", fontsize=13)
plt.legend(); plt.tight_layout(); plt.savefig("age_distribution.png", dpi=150); plt.close()

# 6c. Correlation heatmap (top 20 features by variance)
top20 = X.var().nlargest(20).index.tolist()
plt.figure(figsize=(14, 11))
corr = df[top20 + [TARGET]].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt=".2f", cmap="coolwarm",
            linewidths=0.4, annot_kws={"size": 7})
plt.title("Correlation Heatmap (Top 20 Features)", fontsize=13)
plt.tight_layout(); plt.savefig("correlation_heatmap.png", dpi=150); plt.close()

# 6d. Boxplot — key clinical features
clinical = [c for c in ["GFR", "SerumCreatinine", "BUNLevels", "HbA1c", "ProteinInUrine"] if c in df.columns]
fig, axes = plt.subplots(1, len(clinical), figsize=(14, 5))
for ax, col in zip(axes, clinical):
    df.boxplot(column=col, by=TARGET, ax=ax)
    ax.set_title(col, fontsize=10); ax.set_xlabel("Diagnosis (0=No, 1=CKD)")
plt.suptitle("Key Clinical Feature Distributions by CKD Diagnosis", fontsize=12)
plt.tight_layout(); plt.savefig("clinical_boxplots.png", dpi=150); plt.close()

print("    → Saved: class_distribution.png, age_distribution.png")
print("              correlation_heatmap.png, clinical_boxplots.png")


# ── 7. FEATURE IMPORTANCE (No-Leakage dataset) ────────────
print("\n[7] Computing feature importance on leakage-free dataset ...")
rf_fi = RandomForestClassifier(n_estimators=50, random_state=RANDOM_STATE, n_jobs=-1)
rf_fi.fit(X_tr_nl, y_tr_nl)
feat_imp = pd.Series(rf_fi.feature_importances_,
                     index=X_no_leakage.columns).sort_values(ascending=False)

plt.figure(figsize=(10, 5))
feat_imp.head(15).plot(kind="bar", color="steelblue", edgecolor="black")
plt.title("Top 15 Feature Importances — No-Leakage (Random Forest)", fontsize=13)
plt.ylabel("Importance Score"); plt.xticks(rotation=35, ha="right")
plt.tight_layout(); plt.savefig("feature_importance.png", dpi=150); plt.close()
print("    Top 10 features (no-leakage):")
print(feat_imp.head(10).round(4).to_string())
print("    → Saved: feature_importance.png")


# ── 8. MODEL TRAINING & EVALUATION ───────────────────────
print("\n[8] Training & evaluating models ...")

models = {
    "Logistic Regression" : LogisticRegression(max_iter=500, random_state=RANDOM_STATE),
    "Decision Tree"       : DecisionTreeClassifier(max_depth=8, random_state=RANDOM_STATE),
    "Random Forest"       : RandomForestClassifier(n_estimators=100, random_state=RANDOM_STATE, n_jobs=-1),
    "Gradient Boosting"   : GradientBoostingClassifier(n_estimators=100, random_state=RANDOM_STATE),
    "SVM"                 : SVC(probability=True, kernel="rbf", random_state=RANDOM_STATE),
    "KNN"                 : KNeighborsClassifier(n_neighbors=7, n_jobs=-1),
    "Naive Bayes"         : GaussianNB(),
    **({
        "XGBoost": XGBClassifier(
            n_estimators=100, max_depth=6, eval_metric="logloss",
            random_state=RANDOM_STATE, n_jobs=-1
        )
    } if XGBOOST_AVAILABLE else {}),
    **({
        "LightGBM": LGBMClassifier(
            n_estimators=100, max_depth=6,
            random_state=RANDOM_STATE, n_jobs=-1, verbose=-1
        )
    } if LGBM_AVAILABLE else {}),
    "Extra Trees": ExtraTreesClassifier(
        n_estimators=100, max_depth=6,
        random_state=RANDOM_STATE, n_jobs=-1
    ),
}

# ── Experiment 1: Full features (baseline) ────────────────
print("\n" + "─" * 55)
print("  EXPERIMENT 1 : Full Features (Baseline)")
print("─" * 55)

results_df, roc_data = run_experiment(
    X_train, X_test, y_train, y_test,
    models, scaled_models,
    X_train_sc, X_test_sc,
    label="FULL"
)
results_df_full = results_df.copy()
results_df_full.to_csv("model_comparison.csv", index=False)

# ── Experiment 2: Leakage-free features ───────────────────
print("\n" + "─" * 55)
print("  EXPERIMENT 2 : Leakage-Free Features")
print("─" * 55)

models_nl = copy.deepcopy(models)

results_df_no_leakage, roc_data_nl = run_experiment(
    X_tr_nl, X_te_nl, y_tr_nl, y_te_nl,
    models_nl, scaled_models,
    X_tr_nl_sc, X_te_nl_sc,
    label="NO-LEAKAGE"
)
results_df_no_leakage.to_csv("model_comparison_no_leakage.csv", index=False)


# ── 9. RESULTS TABLE ──────────────────────────────────────
print("\n[9a] Experiment 1 — Full Features (Baseline):")
print(results_df_full.to_string(index=False))
print("     → Saved: model_comparison.csv")

print("\n[9b] Experiment 2 — Leakage-Free Features:")
print(results_df_no_leakage.to_string(index=False))
print("     → Saved: model_comparison_no_leakage.csv")

# ── 9c. PERFORMANCE DROP COMPARISON ───────────────────────
print("\n" + "=" * 55)
print("  PERFORMANCE DROP — Removing Leakage Features")
print("=" * 55)

best_full = results_df_full.iloc[0]
best_nl   = results_df_no_leakage.iloc[0]

acc_drop = round(best_full["Test Accuracy"] - best_nl["Test Accuracy"], 4)
rec_drop = round(best_full["Recall"]        - best_nl["Recall"],        4)

print(f"\n  {'Metric':<20} {'Full':>10} {'No-Leakage':>12} {'Drop':>8}")
print(f"  {'-'*52}")
print(f"  {'Best Model':<20} {best_full['Model']:>10} {best_nl['Model']:>12}")
print(f"  {'Test Accuracy':<20} {best_full['Test Accuracy']:>10.4f} {best_nl['Test Accuracy']:>12.4f} {acc_drop:>+8.4f}")
print(f"  {'Recall':<20} {best_full['Recall']:>10.4f} {best_nl['Recall']:>12.4f} {rec_drop:>+8.4f}")
print(f"  {'ROC-AUC':<20} {best_full['ROC-AUC']:>10.4f} {best_nl['ROC-AUC']:>12.4f} {round(best_full['ROC-AUC']-best_nl['ROC-AUC'],4):>+8.4f}")
print(f"\n  ▶ Accuracy inflation from leakage: {acc_drop:+.2%}")
print("=" * 55)


# ── 10. BEST MODEL — DETAILED REPORT ──────────────────────
best_name  = results_df_full.iloc[0]["Model"]
best_model = models[best_name]
Xtr_best   = X_train_sc if best_name in scaled_models else X_train
Xte_best   = X_test_sc  if best_name in scaled_models else X_test

best_model.fit(Xtr_best, y_train)
y_pred_best = best_model.predict(Xte_best)

print(f"\n[10] Best Model (Full Features) : {best_name}")
print("\n     Classification Report:")
print(classification_report(y_test, y_pred_best, target_names=["Not CKD", "CKD"]))

# ── 10b. BEST MODEL REPORT — NO-LEAKAGE ───────────────────
best_name_nl  = results_df_no_leakage.iloc[0]["Model"]
best_model_nl = models_nl[best_name_nl]
Xtr_best_nl   = X_tr_nl_sc if best_name_nl in scaled_models else X_tr_nl
Xte_best_nl   = X_te_nl_sc if best_name_nl in scaled_models else X_te_nl

best_model_nl.fit(Xtr_best_nl, y_tr_nl)

print(f"\n[10b] Best Model (No-Leakage) : {best_name_nl}")
print("\n      Classification Report (No-Leakage):")
print(classification_report(y_te_nl, best_model_nl.predict(Xte_best_nl),
                             target_names=["Not CKD", "CKD"]))

# ── 10c. SHAP — LEAKAGE-FREE BEST MODEL ───────────────────
if SHAP_AVAILABLE:
    try:
        print(f"\n[10c] SHAP explanation for no-leakage best model: {best_name_nl} ...")
        Xte_shap_nl = pd.DataFrame(Xte_best_nl, columns=X_no_leakage.columns)

        tree_models = {"Random Forest", "Gradient Boosting", "Decision Tree",
                       "Extra Trees", "XGBoost", "LightGBM"}
        if best_name_nl in tree_models:
            explainer   = shap.TreeExplainer(best_model_nl)
            shap_values = explainer.shap_values(Xte_shap_nl)
            sv = shap_values[1] if isinstance(shap_values, list) else shap_values
        elif best_name_nl == "Logistic Regression":
            explainer = shap.LinearExplainer(best_model_nl, X_tr_nl_sc)
            sv        = explainer.shap_values(Xte_shap_nl)
        else:
            explainer = shap.KernelExplainer(
                best_model_nl.predict_proba, shap.sample(Xte_shap_nl, 50)
            )
            sv = explainer.shap_values(Xte_shap_nl)[1]

        plt.figure()
        shap.summary_plot(sv, Xte_shap_nl, plot_type="bar", show=False)
        plt.title(f"SHAP — No-Leakage Model: {best_name_nl}", fontsize=12)
        plt.tight_layout()
        plt.savefig("shap_no_leakage.png", dpi=150)
        plt.close()
        print("    → Saved: shap_no_leakage.png")
    except Exception as e:
        print(f"[10c] SHAP skipped: {e}")
else:
    print("\n[10c] SHAP not available (shap not installed) — skipping.")


# ── 11. CONFUSION MATRIX ──────────────────────────────────
fig, ax = plt.subplots(figsize=(5, 4))
cm = confusion_matrix(y_test, y_pred_best)
ConfusionMatrixDisplay(cm, display_labels=["Not CKD", "CKD"]).plot(
    ax=ax, colorbar=False, cmap="Blues")
ax.set_title(f"Confusion Matrix — {best_name}", fontsize=12)
plt.tight_layout(); plt.savefig("confusion_matrix.png", dpi=150); plt.close()
print("[11] → Saved: confusion_matrix.png")


# ── 12. ROC CURVES — ALL MODELS (Full features) ───────────
plt.figure(figsize=(8, 6))
for name, (fpr, tpr, _) in roc_data.items():
    auc_val = results_df_full[results_df_full["Model"] == name]["ROC-AUC"].values[0]
    plt.plot(fpr, tpr, label=f"{name} (AUC={auc_val:.3f})")
plt.plot([0, 1], [0, 1], "k--", linewidth=0.8)
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.title("ROC Curves — All Models (Full Features)", fontsize=13)
plt.legend(fontsize=8, loc="lower right")
plt.tight_layout(); plt.savefig("roc_curves.png", dpi=150); plt.close()
print("[12] → Saved: roc_curves.png")


# ── 13. ACCURACY BAR CHART ────────────────────────────────
plt.figure(figsize=(10, 5))
colors = ["gold" if n == best_name else "steelblue" for n in results_df_full["Model"]]
bars   = plt.bar(results_df_full["Model"], results_df_full["Test Accuracy"],
                 color=colors, edgecolor="black")
min_acc = results_df_full["Test Accuracy"].min()
plt.ylim(max(0, min_acc - 0.05), 1.01)
plt.ylabel("Test Accuracy"); plt.title("Model Accuracy Comparison (Full Features)", fontsize=13)
plt.xticks(rotation=25, ha="right")
for bar, val in zip(bars, results_df_full["Test Accuracy"]):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,
             f"{val:.3f}", ha="center", va="bottom", fontsize=9)
plt.tight_layout(); plt.savefig("model_accuracy_comparison.png", dpi=150); plt.close()
print("[13] → Saved: model_accuracy_comparison.png")


# ── 14. PRECISION / RECALL / F1 BAR ──────────────────────
metrics_plot = results_df_full[["Model", "Precision", "Recall", "F1-Score"]].set_index("Model")
ax = metrics_plot.plot(kind="bar", figsize=(11, 5), edgecolor="black",
                       color=["#4C72B0", "#DD8452", "#55A868"])
ax.set_ylim(0.5, 1.05); ax.set_ylabel("Score")
ax.set_title("Precision / Recall / F1-Score by Model (Full Features)", fontsize=13)
ax.set_xticklabels(ax.get_xticklabels(), rotation=25, ha="right")
ax.legend(loc="lower right"); plt.tight_layout()
plt.savefig("precision_recall_f1.png", dpi=150); plt.close()
print("[14] → Saved: precision_recall_f1.png")


# ── DONE ──────────────────────────────────────────────────
print("\n" + "=" * 62)
print(f"  PIPELINE COMPLETE")
print(f"  Best model (Full Features) : {best_name}")
print(f"  Best model (No-Leakage)    : {best_name_nl}")
print("  Output files:")
for f in ["class_distribution.png", "age_distribution.png",
          "correlation_heatmap.png", "clinical_boxplots.png",
          "feature_importance.png", "confusion_matrix.png",
          "roc_curves.png", "model_accuracy_comparison.png",
          "precision_recall_f1.png", "model_comparison.csv",
          "model_comparison_no_leakage.csv", "shap_no_leakage.png"]:
    print(f"    • {f}")
print("=" * 62)