version: '3.8'

services:
  frontend:
    build: .
    container_name: ckd_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./saved_models:/app/saved_models
      - ./reports:/app/reports
    command: streamlit run app.py --server.address=0.0.0.0
    restart: unless-stopped
    depends_on:
      - api

  api:
    build: .
    container_name: ckd_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./saved_models:/app/saved_models
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
